//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.24 at 11:40:32 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/nffgInfo", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.polito.dp2.NFFG.sol3.service.jaxb;
