//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.24 at 11:40:32 PM CET 
//


package it.polito.dp2.NFFG.sol3.service.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reachabilityPolicy" type="{http://www.example.org/nffgInfo}reachabilityPolicyType" minOccurs="0"/>
 *         &lt;element name="traversalPolicy" type="{http://www.example.org/nffgInfo}traversalPolicyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reachabilityPolicy",
    "traversalPolicy"
})
@XmlRootElement(name = "policy")
public class Policy {

    protected ReachabilityPolicyType reachabilityPolicy;
    protected TraversalPolicyType traversalPolicy;

    /**
     * Gets the value of the reachabilityPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link ReachabilityPolicyType }
     *     
     */
    public ReachabilityPolicyType getReachabilityPolicy() {
        return reachabilityPolicy;
    }

    /**
     * Sets the value of the reachabilityPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReachabilityPolicyType }
     *     
     */
    public void setReachabilityPolicy(ReachabilityPolicyType value) {
        this.reachabilityPolicy = value;
    }

    /**
     * Gets the value of the traversalPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link TraversalPolicyType }
     *     
     */
    public TraversalPolicyType getTraversalPolicy() {
        return traversalPolicy;
    }

    /**
     * Sets the value of the traversalPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link TraversalPolicyType }
     *     
     */
    public void setTraversalPolicy(TraversalPolicyType value) {
        this.traversalPolicy = value;
    }

}
